### ISSUE TITLE
Error: "target_language = sys.argv[1]"; IndexError: list index out of range.

### ISSUE THREAD

**Issue by diantaowang** [xinebf/google-translate-for-goldendict#14]
#### python version
python 3.8
#### System version
Ubuntu 18.04.3 LTS
## What went wrong
Hi, thanks for your work! When I finished setting as your description, the GoldenDict thrown a error.  
## Reproducing the bug
Traceback (most recent call last):
  File "googletranslate.py", line 125, in <module>
    target_language = sys.argv[1]
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "googletranslate.py", line 125, in <module>
    target_language = sys.argv[1]
IndexError: list index out of range

**Comment by xinebf** [comment]
Command Line :

```
python3 /path/to/googletranslate.py zh-CN %GDWORD%
```

**Comment by diantaowang** [comment]
Thanks！ It solved my problem!  ^_^
