### ISSUE TITLE
好像不支持python 3.10?

### ISSUE THREAD

**Issue by chenxiex** [xinebf/google-translate-for-goldendict#40]
使用python3.10调用报错
使用pip安装的。manjaro linux系统。之前一直用的好好的，某次系统更新之后就出问题了。
`Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details __import__(pkg_name) File "~/.local/lib/python3.10/site-packages/googletranslate/__init__.py", line 17, in <module> translator = Translator(map(lambda x: x.strip(), list(f))) File "~/.local/lib/python3.10/site-packages/googletranslate/client.py", line 39, in __init__ self.token_acquirer = TokenAcquirer(session=self.session, host=service_urls[0]) TypeError: 'map' object is not subscriptable`

**Comment by chenxiex** [comment]
问题解决。重新用pip安装一遍即可。问题close
